version: '3'
services:
 redis:
  image: "redis:alpine"
  command: redis-server --requirepass kapi
  ports:
   - "6379:6379"
  expose:
   - 6379
  restart:
   always
  
 dev:
  image: node:11
  volumes:
   - .:/usr/src/service
  working_dir: /usr/src/service
  command: bash -c "npm install && node ./src/server.js"
  ports:
   - 3333:3333
   - 1235:1235
  expose:
   - 3333
   - 1235
   - 6060
   - 80